name: Actions

on:
  pull_request: {}
  push: {branches: [master]}
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          unityVersion:
            - 2019.4.1f1
          targetPlatform:
            - WebGL
            - StandaloneWindows64
    steps:
      #Checkout
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          lfs: true
          
      #Caches
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
          
      #Test
      - name: Run Tests
        uses: game-ci/unity-test-runner@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
      # Build
      - name: Build project for ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2
        with: 
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
